owner: wakatime
repo: statuspage
user-agent: alanhamlett
sites:
  - name: JAGO
    url: https://www.jagoanssh.com
  - name: API
    url: https://api.wakatime.com/api/v1/meta
  - name: Dashboard
    url: $SECRET_SITE
notifications:
  - type: slack
    channel: C01CHHXFQ3E
assignees:
  - alanhamlett
status-website:
  cname: status.wakatime.com
  logoUrl: https://avatars0.githubusercontent.com/u/4814844?s=200&v=4
  faviconSvg: https://wakatime.com/safari-pinned-tab.svg
  favicon: https://wakatime.com/favicon-32x32.png
  name: WakaTime
  logoHref: https://wakatime.com
  introTitle: WakaTime Status
  introMessage: This page shows **real-time** status of the WakaTime website and API.
  navbar:
    - title: Status
      href: /
    - title: WakaTime Home
      href: https://wakatime.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

